name: recipe_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.3
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.2
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.0
  flutter_timezone: ^1.0.8
  get: 4.6.6
  get_storage: ^2.1.1
  image_picker: ^1.1.1
  intl: ^0.19.0
  palette_generator: ^0.3.3+3
  uuid: ^4.4.0
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
